### ISSUE TITLE
localization error

### ISSUE THREAD

**Issue by renzhuli** [koide3/hdl_localization#10]
Hello, I compiled all the passes according to your installation requirements, but when positioning, the pose did not move, always fluctuating around the starting point. Have you ever encountered such a problem? Thanks a lot!
![2019-01-07 14-42-15](https://user-images.githubusercontent.com/20390399/50753181-eb5cea80-128b-11e9-9f67-0eb6ac0df49a.png)
![2019-01-07 14-54-49](https://user-images.githubusercontent.com/20390399/50753319-78a03f00-128c-11e9-87d8-7fcaffc574e6.png)

**Comment by HappySamuel** [comment]
Hi @renzhuli 

I also have the same problem. How did you solve this issue?

**Comment by trns1997** [comment]
Make sure you are publishing time stamps in the header of your pointcloud topic.

**Comment by wanderingcar** [comment]
Hi, @renzhuli @HappySamuel 

I've also had the same problem, and did you solve this issue? If did, then how?

Thanks!
