### ISSUE TITLE
Step by step tutorial for hdl_localization with docker

### ISSUE THREAD

**Issue by Taeyoung96** [koide3/hdl_localization#106]
@koide3    
Thanks for your great work.  
I made a tutorial to use this repository well using docker.  
- [Tutorial repo](https://github.com/Taeyoung96/hdl_localization_tutorial)  
- [Tutorial video](https://youtu.be/pxeU6HH5Gww)  

If you mention the above in the readme, it would be useful for beginners who use docker. :smile:   

Can I send the PR that I added the above link to the [readme](https://github.com/koide3/hdl_localization/blob/master/README.md)?

I'd appreciate it if you could answer.

**Comment by koide3** [comment]
Wow, great job! I'll definitely be happy to receive a PR for this :+1:
