### ISSUE TITLE
Clarification on the published topic `/aligned_points`

### ISSUE THREAD

**Issue by 0b10010010** [koide3/hdl_localization#108]
Hello all,

I just have a quick question on what exactly the topic `/aligned_points` is supposed to publish. My understanding is that it is points that are aligned with the map at the current instance of lidar reading. But I get dynamic objects that are not present in the map pcd file. Any input is much appreciated. Thanks in advance!

**Comment by koide3** [comment]
Here, "aligned" only means "transformed", and thus aligned_points contains objects not exist in the map.

**Comment by 0b10010010** [comment]
@koide3 thanks for the clarification. Closing the issue now.
