### ISSUE TITLE
Using our own bag file and 3D map

### ISSUE THREAD

**Issue by Jiaminchen0** [koide3/hdl_localization#12]
Hi, sorry to bother you.

I am implementing your algorithm on Ubuntu 16.04, and it worked for your demo data.
But when I used my own bag file and 3D map it says globalmap not received.
Could you please tell me why?

Thanks

**Comment by HappySamuel** [comment]
Hi @Jiaminchen0 

You get a good result when using the demo data, right? I failed to do so. How did you successfully get the demo data works?

Best,
Samuel
