### ISSUE TITLE
Loaded own 3D pointcloud map orientation RPY = 90', 0', 0'

### ISSUE THREAD

**Issue by HappySamuel** [koide3/hdl_localization#15]
![Screenshot from 2019-03-20 17-39-23](https://user-images.githubusercontent.com/18137963/54674336-29ea0d80-4b37-11e9-9060-acbd3c3b061f.png)
![Screenshot from 2019-03-20 17-38-56](https://user-images.githubusercontent.com/18137963/54674337-29ea0d80-4b37-11e9-9607-45568175d193.png)

Hi,

I have recorded my own 3D pointcloud map and wanna to try it out with hdl_localization package. However, the loaded map orientation if off the plane with RPY=90', 0', 0'
How should i correct the orientation of the loaded 3D pointcloud map?

I use ROS package "pointcloud_to_pcd" to save the map.

Best.
Samuel

**Comment by HappySamuel** [comment]
Problem solved while waiting for answer...

For .pcd files, just open it with gedit. Then modify the following arguments...
FIELDS y z x intensity
![Screenshot from 2019-03-20 22-11-04](https://user-images.githubusercontent.com/18137963/54690829-2cf7f480-4b5d-11e9-9125-182089195ab8.png)

By modifying the x y z location, can change the orientation of the pointcloud map.

**Comment by walterchenchn** [comment]
Hi,

After i modify the .PCD file, and save the file, the file was been corrupted. How can i open the .PCD file with gedit?

**Comment by HappySamuel** [comment]
Hi @walterchenchn 

That's weird. Can you backup the .pcd file, and then try it again.

Best,
Samuel
