### ISSUE TITLE
Can't align pointcloud with the prior map

### ISSUE THREAD

**Issue by Yukina1996** [koide3/hdl_localization#20]
![image](https://user-images.githubusercontent.com/16861976/62422679-fcb68a00-b6e8-11e9-9ff5-8154ef39752d.png)
 I tried the data that auhor give. But the result is bad, the point cloud can't align well with the prior map. I don't understang why this could happen.

**Comment by koide3** [comment]
Hi @Yukina1996 ,
Could you try to slow down the playback speed to see if it's a matter of the processing speed? like:
```
rosbag play --clock -r 0.2 hdl_400.bag
```

**Comment by Yukina1996** [comment]
thank you so much. The result seems very nice.
![image](https://user-images.githubusercontent.com/16861976/62677393-c460c580-b9e0-11e9-8cc8-5618c7f39989.png)
