### ISSUE TITLE
Failing to track after a few seconds?

### ISSUE THREAD

**Issue by wiku30** [koide3/hdl_localization#25]
Hi,
When I run it with the default launch file (hdl_localization.launch) and the hdl_400.bag, it seems to work for the first few frames, but it stopped moving after a while, seeming to have lost the track.
So in the video provided in the readme, did you use the original launch file, or have you modified some settings?
Thanks.

**Comment by wiku30** [comment]
BTW, I feel that the concentric rings on the ground might affect the tracking as they are likely to be static relative to the car instead of the map. Could you briefly tell me how you have solved this problem...

**Comment by txshang** [comment]
I have met the same question with you.You can try to adjust the downsample to 0.5 and have a try.

**Comment by wiku30** [comment]
@txshang 

I tried it and the tracking persists a few more frames, but still lose after that. I wonder if there is any "debug" message in this package like hdl_graph_slam.

**Comment by wiku30** [comment]
@txshang
Solved with another way, but thanks anyway

**Comment by WilliamWoo45** [comment]
@wiku30 Hi Zishuo. I'm having the same problem with you. Could you brief me how you managed to solve it?
