### ISSUE TITLE
ERROR: Unable to communicate with master!

### ISSUE THREAD

**Issue by JSRGFJZ** [koide3/hdl_localization#3]
Hi, @koide3 
when I input that " rosparam set use_sim_time true", there is the error "ERROR: Unable to communicate with master!"?
what happened?

**Comment by koide3** [comment]
Hi, 
First of all, you need to start *roscore* before using ROS.
Please see http://wiki.ros.org/ROS/Tutorials/UnderstandingNodes for ROS basics.
