### ISSUE TITLE
Losing Localization. Please help 

### ISSUE THREAD

**Issue by vimalrajayyappan** [koide3/hdl_localization#30]
Dear friend,

Thanks for the package.
I had tried using your package for localization where I found some drifts in localization even when Im fusing with IMU.

I used DIRECT7 method for registrationa and localization
NDT_OMP

I saved map at 0.01 resolution

when I try to localize i found some warning like
"Leaf size is too small for the input dataset. Integer indices would overflow."

I altered downsample_resolution and checked as well. Couldnt figure.I attached a localization config file screenshot.Please check.
![hdl_launch](https://user-images.githubusercontent.com/36330391/67765904-422ded80-fa73-11e9-9a47-9ed83b8782aa.png)

Kindly help me to gain the accuracy.
Suggest me some steps.

Thanks a lot

**Comment by koide3** [comment]
Hi @vimalrajayyappan ,
Maybe your map is too large for voxelgrid filtering. Change VexelGrid in the following line to ApproximateVoxelGrid which can handle smaller resolutions.

https://github.com/koide3/hdl_localization/blob/624a7613d1639fefc0f67934e4f57dd2a8c9878f/apps/globalmap_server_nodelet.cpp#L58

**Comment by vimalrajayyappan** [comment]
Thanks a lot Koi. I will give a try.
Following which can you please share some values of params in Mapping&Localization and their insights. So that I can tune and check their optimality.

Another qn pls:
Should initial pose be highly accurate? Once I give the initial pose whether the algorithm tries to match the best position nearby, before I start moving?

**Comment by koide3** [comment]
The following guide would be helpful to tune the parameters.
https://github.com/koide3/hdl_graph_slam#the-mapping-result-is-poor-parameter-tuning-guide

The initial pose should be close to the actual pose (in particular, a large rotational error may affect the convergence). Once you give the initial pose, it updates the estimated pose even if the sensor is fixed.

**Comment by fatmanurgezmiss** [comment]
> ctual pose (in particular, a large rotational error may affect the convergence). Once you give the initial pose, it updates the estimated pose even if the sensor is fixed.



> The following guide would be helpful to tune the parameters. https://github.com/koide3/hdl_graph_slam#the-mapping-result-is-poor-parameter-tuning-guide
> 
> The initial pose should be close to the actual pose (in particular, a large rotational error may affect the convergence). Once you give the initial pose, it updates the estimated pose even if the sensor is fixed.



Hi,
I have the same issue that called "Leaf size is too small for the input dataset. Integer indices would overflow."  Then I saw yor answer for that. When I try ApproximateVoxelGrid terminal issue gones but localization fail is continues. Can you help me for that?
