### ISSUE TITLE
how to tune the parameters?

### ISSUE THREAD

**Issue by liuyf5231** [koide3/hdl_localization#31]
Hi koide3,
     my launch params,
   ```       
 <param name="ndt_neighbor_search_method" value="DIRECT7" />
   <param name="ndt_resolution" value="6.0" />
     <param name="downsample_resolution" value="2.0" />
```  

     the ndt align drift a little,how can I tune the ndt parameters？

![1](https://user-images.githubusercontent.com/47884441/68723799-ac5a9c80-05f4-11ea-8e44-ac2b87487aba.png)
![2](https://user-images.githubusercontent.com/47884441/68723819-b8465e80-05f4-11ea-82ee-ab4c49b8ac12.png)

**Comment by koide3** [comment]
Hi @liuyf5231 ,
downsample_resolution = 2.0 is too large. Set a smaller value (e.g., 0.1) to it.
