### ISSUE TITLE
imu frame

### ISSUE THREAD

**Issue by liuyf5231** [koide3/hdl_localization#33]
Hi koide3,
  which frame does imu use in hdl localization? front left up?

**Comment by koide3** [comment]
Hi @liuyf5231 ,
Yes, the IMU frame is the same as the LIDAR frame (XYZ=front-left-up).

**Comment by liuyf5231** [comment]
> Hi @liuyf5231 ,
> Yes, the IMU frame is the same as the LIDAR frame (XYZ=front-left-up).

but when i set use_imu true, localization will drift a lot,e.g 100m

**Comment by liuyf5231** [comment]
I got the reason, the time stamp in IMU data is wrong.
But when i use imu,the localization accuracy not impoved(max error,0.3m).
