### ISSUE TITLE
Seems to me the UFK is almost bypassed

### ISSUE THREAD

**Issue by bugerry87** [koide3/hdl_localization#41]
Thanks for sharing your awesome project.

However, I wonder the prediction part of PoseSystem that almost copies the past state expect of some portion of the gyro.
Velocity stays 0 since it gets continuously updated by itself.
Position is from the past frame.

Or do I misunderstand?

**Comment by koide3** [comment]
Hi @bugerry87 ,
We empirically found that introducing acceleration affects the estimation stability (in our setting with a noisy acc sensor). So, we use only angular velocity to update the state in the prediction step, and thus the velocity does not change during this step. 

More important part is the correction step that updates all the state parameters including position, velocity, bias, etc. by integrating the prediction result and the scan matching result. The velocity is changed during this step, and thus, in the next prediction step, the position will be shifted with this estimated velocity.

**Comment by bugerry87** [comment]
Wow! Thanks for this explanation.
