### ISSUE TITLE
failed after use gicp as registration method

### ISSUE THREAD

**Issue by Pigrubby** [koide3/hdl_localization#57]
Hello Koide3,

Failed after use gicp as registration method, please take a look.
Just changed the launch: param name="ndt_neighbor_search_method" value="GICP_OMP" 

SUMMARY
========

PARAMETERS
 * /globalmap_server_nodelet/downsample_resolution: 0.1
 * /globalmap_server_nodelet/globalmap_pcd: /home/Andy/Hun...
 * /hdl_localization_nodelet/cool_time_duration: 2.0
 * /hdl_localization_nodelet/downsample_resolution: 0.2
 * /hdl_localization_nodelet/init_ori_w: 1.0
 * /hdl_localization_nodelet/init_ori_x: 0.0
 * /hdl_localization_nodelet/init_ori_y: 0.0
 * /hdl_localization_nodelet/init_ori_z: 0.0
 * /hdl_localization_nodelet/init_pos_x: 0.0
 * /hdl_localization_nodelet/init_pos_y: 0.0
 * /hdl_localization_nodelet/init_pos_z: 0.0
 * /hdl_localization_nodelet/invert_imu: False
 * /hdl_localization_nodelet/ndt_neighbor_search_method: GICP_OMP
 * /hdl_localization_nodelet/ndt_resolution: 1.0
 * /hdl_localization_nodelet/odom_child_frame_id: rslidar
 * /hdl_localization_nodelet/specify_init_pose: True
 * /hdl_localization_nodelet/use_imu: False
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    globalmap_server_nodelet (nodelet/nodelet)
    hdl_localization_nodelet (nodelet/nodelet)
    velodyne_nodelet_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[velodyne_nodelet_manager-1]: started with pid [30408]
process[globalmap_server_nodelet-2]: started with pid [30409]
process[hdl_localization_nodelet-3]: started with pid [30410]
[ INFO] [1607161930.052632541]: Initializing nodelet with 12 worker threads.
[ INFO] [1607161930.185192853]: search_method GICP_OMP is selected
[ INFO] [1607161930.185621808]: initialize pose estimator with specified parameters!!
[ INFO] [1607161930.241544730]: globalmap received!
nodelet: /build/pcl-OilVEB/pcl-1.8.1+dfsg1/kdtree/include/pcl/kdtree/impl/kdtree_flann.hpp:136: int pcl::KdTreeFLANN<PointT, Dist>::nearestKSearch(const PointT&, int, std::vector<int>&, std::vector<float>&) const [with PointT = pcl::PointXYZI; Dist = flann::L2_Simple<float>]: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to nearestKSearch!"' failed.
[velodyne_nodelet_manager-1] process has died [pid 30408, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=velodyne_nodelet_manager __log:=/home/Andy/.ros/log/a885c078-36cf-11eb-8db8-983b8fd5befc/velodyne_nodelet_manager-1.log].
log file: /home/Andy/.ros/log/a885c078-36cf-11eb-8db8-983b8fd5befc/velodyne_nodelet_manager-1*.log
[globalmap_server_nodelet-2] process has finished cleanly
log file: /home/Andy/.ros/log/a885c078-36cf-11eb-8db8-983b8fd5befc/globalmap_server_nodelet-2*.log
[hdl_localization_nodelet-3] process has finished cleanly
log file: /home/Andy/.ros/log/a885c078-36cf-11eb-8db8-983b8fd5befc/hdl_localization_nodelet-3*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by numb0824** [comment]
hi, i have met the same error,could you please help me how to solve it
