### ISSUE TITLE
About the 2D static map

### ISSUE THREAD

**Issue by xiangxiang123456** [koide3/hdl_localization#75]
When we start the hdl_localization.launch, there is a warning 
`[ WARN] [1618565528.753417772]: Num points in the sliced map is too small!!
[ WARN] [1618565528.753497341]: Change the slice range parameters!!
`
And the 2D static map doesn't appear. We want to know if the slice range parameters causes this situation and how to adjust the parameters.

Thank you very much!

**Comment by xiangxiang123456** [comment]
I got it! It's in bbs_config.yaml!

**Comment by lingdameng** [comment]
How to modify the parameters in bbs_config.yaml file to avoid this warning?
Thanks very much!
