### ISSUE TITLE
hdl_global_localization-2 process has died

### ISSUE THREAD

**Issue by kunnalparihar** [koide3/hdl_localization#78]
Hii, I tried installing HDL localisation. I compiled successfully using catkin_make but it crashes when I run roslaunch hdl_localization hdl_localization.launch.

I got this message:
started core service [/rosout]
process[hdl_global_localization-2]: started with pid [15425]
process[velodyne_nodelet_manager-3]: started with pid [15426]
process[globalmap_server_nodelet-4]: started with pid [15427]
process[hdl_localization_nodelet-5]: started with pid [15428]
[ INFO] [1621421451.679460109]: Initializing nodelet with 4 worker threads.
[ INFO] [1621421451.779751982]: Start Global Localization Node
[ INFO] [1621421451.846102225]: create registration method for localization
[ INFO] [1621421451.849331871]: NDT_OMP is selected
[ INFO] [1621421451.851138337]: search_method DIRECT7 is selected
[ INFO] [1621421451.851184390]: create registration method for fallback during relocalization
[ INFO] [1621421451.854544914]: NDT_OMP is selected
[ INFO] [1621421451.854611162]: search_method DIRECT7 is selected
[ INFO] [1621421451.855598962]: initialize pose estimator with specified parameters!!
[ INFO] [1621421451.878691375]: wait for global localization services
[ INFO] [1621421453.754945929]: globalmap received!
[ INFO] [1621421453.954714828]: set globalmap for global localization!
[ INFO] [1621421454.069971328]: Global Map Received
[ INFO] [1621421454.348819468]: failed to set global map
[hdl_global_localization-2] process has died [pid 15425, exit code -11, cmd /home/kunal/HDL_localisation/devel/lib/hdl_global_localization/hdl_global_localization_node __name:=hdl_global_localization __log:=/home/kunal/.ros/log/13491260-b890-11eb-a1cc-48bf6be52808/hdl_global_localization-2.log].
log file: /home/kunal/.ros/log/13491260-b890-11eb-a1cc-48bf6be52808/hdl_global_localization-2*.log

I have Ubuntu, ROS melodic, PCL 1.8 installed.
Can you please help me?

thank you in advance

**Comment by numb0824** [comment]
hi , i have met the same error,could you please tell me how to solve it
