### ISSUE TITLE
Delta time (dt) variable inside pose_system.hpp

### ISSUE THREAD

**Issue by kunnalparihar** [koide3/hdl_localization#82]
I am a little confused as to how did you choose dt as 0.01?
https://github.com/koide3/hdl_localization/blob/master/include/hdl_localization/pose_system.hpp#L21
Imu frequency is 200 Hz
I guess dt should be equal to (1 / imu_frequency)

Thank you in advance

**Comment by koide3** [comment]
Yes, you are correct, and ```dt``` will be updated based on the last and current data timestamps.

https://github.com/koide3/hdl_localization/blob/1cdef711d66fdb4ec8969623dd2568eb3f45ce25/src/hdl_localization/pose_estimator.cpp#L66

**Comment by kunnalparihar** [comment]
okay, I got it. thanks
