### ISSUE TITLE
Cannot get a stable localization result

### ISSUE THREAD

**Issue by Shangareer** [koide3/hdl_localization#86]
Hi, I used 'hdl_400.bag' to build a map and do localization, however the localization result was always unstable even if I tried to change the arguments 'use_imu', 'invert_imu_acc', 'invert_imu_gyro' to 'true' or 'false'. Are there any other parameters to be set?
Any one who can help? thanks.

**Comment by RaviBeagle** [comment]
Hi @Shangareer,

Was there a solution ? I find that if we enable use_imu with or without the invert parameters, the hdl_localization is not working at all..
