### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by grassjelly** [koide3/hdl_localization#96]
HI, just curious will ROS2 support be part of your roadmap? Thank you!

**Comment by koide3** [comment]
I will not add a ROS2 support for this package because I'm planning to release a new localization package with ROS1/ROS2 support.

**Comment by grassjelly** [comment]
Thanks for your reply. Do you have a rough estimate of its release date? Looking forward. Thank you

**Comment by koide3** [comment]
I expect it would be around Jan ~ Mar in 2023 (can largely vary).

**Comment by grassjelly** [comment]
Got it. Thank you!

**Comment by Alex-Beh** [comment]
@grassjelly Maybe you can check this [repo](https://github.com/DataspeedInc/hdl_localization/tree/ros2) for ROS2 Implementation of hdl_localization.

@koide3 May I know the difference between hdl_localization & the new coming localization package? Do you have any preprint paper for that?

**Comment by grassjelly** [comment]
Thanks @Alex-Beh. Have you tried this ROS2 port yet?

**Comment by koide3** [comment]
> @koide3 May I know the difference between hdl_localization & the new coming localization package? Do you have any preprint paper for that?

I wrote it from scratch with the tight coupling LiDAR and IMU costs that make it extremely robust to sensor motion and degeneration. I will submit it to some conference but the manuscript has not been available yet. Stay tuned!

**Comment by grassjelly** [comment]
@koide3 that sounds really promising. Looking forward to the release. Do you happen to know more 3D localization algorithm that supports ROS2?

**Comment by pyc5714** [comment]
@grassjelly @koide3   Did you implement the hdl_localization using this [repo](https://github.com/DataspeedInc/hdl_localization/tree/ros2) in ROS2??

I'm trying to get that going, but I haven't running yet because there seems to be some errrors I need to fix with the dependecy and launch file..
